// <auto-generated />
using System;
using Game_Unity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_Unity.Migrations.AvatarLocation
{
    [DbContext(typeof(AvatarLocationContext))]
    [Migration("20240416183611_Inicial1.")]
    partial class Inicial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_Unity.Models.AvatarLocationModel", b =>
                {
                    b.Property<int>("AvatarLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvatarLocationId"));

                    b.Property<decimal?>("CoordinatesX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoordinatesY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CoordinatesZ")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DetectiveId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("AvatarLocationId");

                    b.ToTable("AvatarLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
