// <auto-generated />
using Game_Unity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_Unity.Migrations.CropPests
{
    [DbContext(typeof(CropPestsContext))]
    [Migration("20240416125834_Inicial3")]
    partial class Inicial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_Unity.Models.CropPestsModel", b =>
                {
                    b.Property<int>("Crop")
                        .HasColumnType("int");

                    b.Property<int>("Plague")
                        .HasColumnType("int");

                    b.ToTable("Crop_Pests");
                });
#pragma warning restore 612, 618
        }
    }
}
